steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: wolfderechter/expense-tracker-frontend
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: main
  event: push
